### ISSUE TITLE
请问application初始化时new MainActivity的意义是什么？

### ISSUE THREAD

**Issue by mudelong** [aiceking/AppStartFaster#1]
在attachBaseContext中new SplashActivity()和MainActivity这么做是否有效果，没看懂，能否解答一下呢，谢谢！

**Comment by aiceking** [comment]
> 在attachBaseContext中new SplashActivity()和MainActivity这么做是否有效果，没看懂，能否解答一下呢，谢谢！

和类加载原理有关，预加载可以加快类的创建速度，具体百度一下吧

**Comment by mudelong** [comment]
谢谢，还有两个问题，
1、在非主进程，是否没必要去用AppStartTaskDispatcher，我看判断了是主进程才去优化。非主进程的活动是否肯定不会影响启动速度？
2、如果我要确保一些初始化是必须在Application的Oncreate结束前阻塞执行的，那么将该task设置needWait为true，是这个意思吧。
感谢！

**Comment by aiceking** [comment]
> 谢谢，还有两个问题，
> 1、在非主进程，是否没必要去用AppStartTaskDispatcher，我看判断了是主进程才去优化。非主进程的活动是否肯定不会影响启动速度？
> 2、如果我要确保一些初始化是必须在Application的Oncreate结束前阻塞执行的，那么将该task设置needWait为true，是这个意思吧。
> 感谢！

1、非主进程的目的是Android 4.4 MultDex的加载用的，加载完进程就kill掉了，可以百度一下MultDex冷启动优化。
2、区分开是否在主进程就是为了只要在主进程才用AppStartTaskDispatcher开启需要的任务。

**Comment by aiceking** [comment]
> 谢谢，还有两个问题，
> 1、在非主进程，是否没必要去用AppStartTaskDispatcher，我看判断了是主进程才去优化。非主进程的活动是否肯定不会影响启动速度？
> 2、如果我要确保一些初始化是必须在Application的Oncreate结束前阻塞执行的，那么将该task设置needWait为true，是这个意思吧。
> 感谢！

其实我readme里有写为哈这么做，没写细节，嘿嘿，可以自己研究一下，也不是很复杂。
