### ISSUE TITLE
需要在主线程执行的任务没办法设置依赖任务吧？

### ISSUE THREAD

**Issue by duan101101** [aiceking/AppStartFaster#2]
否则主线程就直接阻塞住了

**Comment by aiceking** [comment]
> 否则主线程就直接阻塞住了

可以的，主线程的任务会按依赖顺序排好

**Comment by duan101101** [comment]
> > 否则主线程就直接阻塞住了
> 可以的，主线程的任务会按依赖顺序排好

依赖顺序没问题，但是

**Comment by duan101101** [comment]
> > 否则主线程就直接阻塞住了
> 
> 可以的，主线程的任务会按依赖顺序排好
依赖顺序没问题，但是这样主线程会长时间处于阻塞状态，等待依赖子线程执行的结束
