### ISSUE TITLE
希望一批任务执行完后能将任务都清楚掉

### ISSUE THREAD

**Issue by Destroyer716** [aiceking/AppStartFaster#3]
有些任务在Application里面使用这个启动器去处理了，还有一些任务想在初始化完成后也用这个启动器去处理。
但是发现，延时处理的任务在执行时会将之前添加的任务再次执行。
或者每执行完一个Task就马上移除这个Task.

**Comment by NoEndToLF** [comment]
确实是一个优化点，没考虑过会二次调用，我最迟会在明天晚上发布改动后的版本，执行完一个task后进行移除。
感谢您的建议~，新年快乐！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NoEndToLF/AppStartFaster"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月21日(星期天) 晚上6:49
收件人:&nbsp;"NoEndToLF/AppStartFaster"<AppStartFaster@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[NoEndToLF/AppStartFaster] 希望一批任务执行完后能将任务都清楚掉 (#3)





 
有些任务在Application里面使用这个启动器去处理了，还有一些任务想在初始化完成后也用这个启动器去处理。
 但是发现，延时处理的任务在执行时会将之前添加的任务再次执行。
 或者每执行完一个Task就马上移除这个Task.

**Comment by NoEndToLF** [comment]
> 有些任务在Application里面使用这个启动器去处理了，还有一些任务想在初始化完成后也用这个启动器去处理。
> 但是发现，延时处理的任务在执行时会将之前添加的任务再次执行。
> 或者每执行完一个Task就马上移除这个Task.

每执行完一个Task就马上移除这个Task可行也很合理，但是重新调用start()后，没完成的任务和新添加的任务还会重新进行拓扑排序，可能会导致一些还没有执行完的任务出现问题，又或者

**Comment by aiceking** [comment]
> 有些任务在Application里面使用这个启动器去处理了，还有一些任务想在初始化完成后也用这个启动器去处理。
> 但是发现，延时处理的任务在执行时会将之前添加的任务再次执行。
> 或者每执行完一个Task就马上移除这个Task.

每执行完一个Task就马上移除这个Task这个确实需要实现，我会在近期发布下个版本，但是如果之前add的task没有执行完，又添加了新的task，调用start()后还会重新进行拓扑排序并开始当前的所有任务，可能所有的在等待执行的任务执行顺序都变了，一些还没执行完的任务会导致再次执行，和这个库的逻辑有些冲突和不可控，如逻辑不太复杂，就是延迟初始化某些东西，个人建议可自行实现，我也会思考一下是否有比较好的解决方案来支撑

**Comment by aiceking** [comment]
> 有些任务在Application里面使用这个启动器去处理了，还有一些任务想在初始化完成后也用这个启动器去处理。 但是发现，延时处理的任务在执行时会将之前添加的任务再次执行。 或者每执行完一个Task就马上移除这个Task.

新版本2.0.0已实现
