### ISSUE TITLE
线程优先级问题

### ISSUE THREAD

**Issue by lcj0304** [aiceking/AppStartFaster#5]
如果使用者，不重载AppStartTask的priority 又设置允许在主线程运行，是不是主线程就会被设置成后台线程了。

**Comment by lvjiancong** [comment]
AppStartTaskRunnable内部设置了Process.setThreadPriority(appStartTask.priority());导致主线程优先级变低，导致UI卡顿

**Comment by lvjiancong** [comment]
Process.setThreadPriority(appStartTask.priority());如果去掉是否有什么影响，或者我判断是主线程就不处理，是否可行

**Comment by aiceking** [comment]
> Process.setThreadPriority(appStartTask.priority());如果去掉是否有什么影响，或者我判断是主线程就不处理，是否可行

去掉没问题，这几天会出个版本，做个优化

**Comment by aiceking** [comment]
> Process.setThreadPriority(appStartTask.priority());如果去掉是否有什么影响，或者我判断是主线程就不处理，是否可行

已发布2.2.0版本，只有在非主线程任务才设置线程优先级
