### ISSUE TITLE
有隐私整改问题,作者方便改下吗

### ISSUE THREAD

**Issue by LvBing1995** [aiceking/AppStartFaster#6]
场景1：APP未见向用户告知且未经用户同意，在YYY功能中，存在收集通讯录、短信、通话记录、相机等信息的行为，非服务所必需且无合理应用场景，超出与收集个人信息时所声称的目的具有直接或合理关联的范围。
场景2：APP向用户明示SDK的收集使用规则，但未见清晰明示SDK收集设备MAC地址、软件安装列表等的目的方式范围，用户同意隐私政策后，SDK存在收集设备MAC地址、软件安装列表的行为。

获取运行中进程信息

**Comment by aiceking** [comment]
> 场景1：APP未见向用户告知且未经用户同意，在YYY功能中，存在收集通讯录、短信、通话记录、相机等信息的行为，非服务所必需且无合理应用场景，超出与收集个人信息时所声称的目的具有直接或合理关联的范围。 场景2：APP向用户明示SDK的收集使用规则，但未见清晰明示SDK收集设备MAC地址、软件安装列表等的目的方式范围，用户同意隐私政策后，SDK存在收集设备MAC地址、软件安装列表的行为。
> 
> 获取运行中进程信息

使用最新版本，内部已经将是否是主进程的判断去掉了

**Comment by lvjiancong** [comment]
您好，您说的最新版，是指哪个版本，我看您的回复时间是在2.0.0版本(Nov 23, 2021)之后，但最新的是2.0.0版本。
ProcessUtil，还是有判断主进程的方法

**Comment by aiceking** [comment]
> 您好，您说的最新版，是指哪个版本，我看您的回复时间是在2.0.0版本(Nov 23, 2021)之后，但最新的是2.0.0版本。 ProcessUtil，还是有判断主进程的方法

就是从2.0.0开始，ProcessUtil只是提供判断主进程的方法，他只是作为[AppStartFaster]这个库里的一个工具类，[AppStartFaster]内部的功能并不会调用ProcessUtil，作为一个工具类，只要你不用它，自然不会有隐私整改问题

**Comment by aiceking** [comment]
> 您好，您说的最新版，是指哪个版本，我看您的回复时间是在2.0.0版本(Nov 23, 2021)之后，但最新的是2.0.0版本。 ProcessUtil，还是有判断主进程的方法

可以使用2.1.0版本，把ProcessUtil删掉了，[AppStartFaster]本身并不需要判断是否主进程的功能。
